In [1]:
import os
import numpy as np
import pandas as pd
from PIL import Image

In [3]:
def load_image(modelId, labels, imgWidth, imgHeight):
    imgList = []
    labelList = []
    for label in labels:
        imgDir = os.path.join('models', modelId, label)
        print(imgDir)
        for fileName in os.listdir(imgDir):
            if fileName.endswith(('.jpg', '.png', '.jpeg')):
                imgName = os.path.join(str(imgDir),fileName)
                img = Image.open(imgName).resize((imgWidth, imgHeight))
                img_arr = np.array(img)
                imgList.append(img_arr)
                labelList.append(label)
    print("이미지 리스트에 담기 완료")
    imgList = np.array(imgList) / 255.0
    print("이미지 ndarray로 전환하고 정규화 완료")
    return imgList, labelList

In [19]:
labels = ['Bear','Bird','Cat','Cow','Deer']
X, y= load_image('animal1', labels, 224, 224)
print(X[1])

models\animal1\Bear
models\animal1\Bird
models\animal1\Cat
models\animal1\Cow
models\animal1\Deer
이미지 리스트에 담기 완료
이미지 ndarray로 전환하고 정규화 완료
[[[0.61176471 0.6627451  0.62352941]
  [0.60392157 0.65882353 0.60784314]
  [0.61176471 0.6627451  0.59607843]
  ...
  [0.94509804 0.94901961 0.96862745]
  [0.94509804 0.94901961 0.96862745]
  [0.94509804 0.94901961 0.96862745]]

 [[0.61568627 0.66666667 0.62745098]
  [0.59607843 0.65098039 0.6       ]
  [0.59215686 0.64313725 0.57647059]
  ...
  [0.94117647 0.94509804 0.96470588]
  [0.9372549  0.94117647 0.96078431]
  [0.9372549  0.94117647 0.96078431]]

 [[0.58823529 0.64313725 0.59215686]
  [0.58039216 0.63529412 0.57647059]
  [0.58431373 0.63137255 0.57647059]
  ...
  [0.93333333 0.9372549  0.95686275]
  [0.93333333 0.9372549  0.95686275]
  [0.92941176 0.93333333 0.95294118]]

 ...

 [[0.59215686 0.56078431 0.50980392]
  [0.44313725 0.41960784 0.36470588]
  [0.24705882 0.22352941 0.16862745]
  ...
  [0.58039216 0.52156863 0.44705882]
  [0.6      

In [28]:
y = pd.get_dummies(y)
print(y)

      Bear   Bird    Cat    Cow   Deer
0     True  False  False  False  False
1     True  False  False  False  False
2     True  False  False  False  False
3     True  False  False  False  False
4     True  False  False  False  False
..     ...    ...    ...    ...    ...
638  False  False  False  False   True
639  False  False  False  False   True
640  False  False  False  False   True
641  False  False  False  False   True
642  False  False  False  False   True

[643 rows x 5 columns]


In [31]:
t = True
print(type(t))

<class 'bool'>
